### ISSUE TITLE
bug: 分支26 make后报错：Illegal instruction

### ISSUE THREAD

**Issue by kid7995** [shibo-SWD/VisionSoftware#44]
1.尝试在src/cmakelist中注释掉PCL ${PCL_LIBRARIES} 仍然报错
2.gdb中编译 调整为单步 报错信息显示位置在
`/usr/include/boost/math/special_functions/erf.hpp:373
warning: Source file is more recent than executable.
373              hi = floor(ldexp(frexp(z, &expon), 26));`
3.打入断点后 单步运行还是在boost的各个文件跳转 最后到erf.hpp:373 为止 报错：
`Thread 1 "SaiwiderVision" received signal SIGILL, Illegal instruction.
0x00007fffea20c66d in boost::math::detail::erf_imp<double, boost::math::policies::policy<boost::math::policies::promote_float<false>, boost::math::policies::promote_double<false>, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy, boost::math::policies::default_policy> > (z=z@entry=2.25, invert=true, invert@entry=false, t=..., pol=...) at /usr/include/boost/math/special_functions/erf.hpp:373
373              hi = floor(ldexp(frexp(z, &expon), 26));`
4.boost库涉及的代码文件有`kuka_eki_hw_interface.cpp`;`point_cloud.cpp`

**Comment by kid7995** [comment]
将main.cpp文件中涉及 kuka::eki的相关代码注释掉 相关的UIcompent中设计kuka::eki输入注释掉 make后运行 仍然报错 Illegal instruction
怀疑是程序执行的初始化过程中报的错误

**Comment by kid7995** [comment]
在分支commit历史中 对比了可运行的和现在up-to-date版 多处位置添加了PCL库的引用
![image](https://github.com/shibo-SWD/VisionSoftware/assets/116342140/7cc9c383-e81d-4e40-a31b-973c4da6c9bf)
尝试在环境中重新安装PCL库 解决报错

**Comment by shibo-SWD** [comment]
> 在分支commit历史中 对比了可运行的和现在up-to-date版 多处位置添加了PCL库的引用 ![image](https://private-user-images.githubusercontent.com/116342140/331114859-7cc9c383-e81d-4e40-a31b-973c4da6c9bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NTMwMTUsIm5iZiI6MTcxNTg1MjcxNSwicGF0aCI6Ii8xMTYzNDIxNDAvMzMxMTE0ODU5LTdjYzljMzgzLWU4MWQtNGU0MC1hMzFiLTk3M2M0ZGE2YzliZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQwOTQ1MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODYzYzEyMzJhMjJiNmI3MDAzNWQ2ZjBiZGJkNjU1OTYyYzc0NmE1YzdkOGE5ZTY3ODM0YTMwYzUzYjQ5YmY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BsfPWZdS0yrLdsSNhbPa81hteg5jhGAs0M7ZBP6V0h4) 尝试在环境中重新安装PCL库 解决报错

- 如何安装PCL库，使用sudo apt install 还是使用源码下载然后build
- 版本号是多少，10还是13

**Comment by kid7995** [comment]
> > 在分支commit历史中 对比了可运行的和现在up-to-date版 多处位置添加了PCL库的引用 ![image](https://private-user-images.githubusercontent.com/116342140/331114859-7cc9c383-e81d-4e40-a31b-973c4da6c9bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NTMwMTUsIm5iZiI6MTcxNTg1MjcxNSwicGF0aCI6Ii8xMTYzNDIxNDAvMzMxMTE0ODU5LTdjYzljMzgzLWU4MWQtNGU0MC1hMzFiLTk3M2M0ZGE2YzliZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQwOTQ1MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODYzYzEyMzJhMjJiNmI3MDAzNWQ2ZjBiZGJkNjU1OTYyYzc0NmE1YzdkOGE5ZTY3ODM0YTMwYzUzYjQ5YmY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BsfPWZdS0yrLdsSNhbPa81hteg5jhGAs0M7ZBP6V0h4) 尝试在环境中重新安装PCL库 解决报错
> 
> * 如何安装PCL库，使用sudo apt install 还是使用源码下载然后build
> * 版本号是多少，10还是13

之前尝试apt安装 是1.12版本 原来的1.13是源码下载后build安装的 这两个如果都在路径里 cmake find package指令好像没找到1.12版本的  make的记录中依旧是1.13

**Comment by kid7995** [comment]
问题解决 
1.通过apt指令安装PCL 1.12版本
2.在src/cmakelist中 添加PCL1.12版本的路径（该路径为pclconfig.make文件所在的路径）
`set(PCL_DIR "/usr/lib/x86_64-linux-gnu/cmake/pcl/") find_package(PCL 1.12 REQUIRED PATHS ${PCL_DIR} NO_DEFAULT_PATH)
include_directories(${PCL_INCLUDE_DIRS})`
